version: '3.4'

services:
  mysqldb:
    image: mysql:latest
    hostname: mysqldb
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: mgis_dev
      # MYSQL_USER: root
      MYSQL_PASSWORD: admin
    volumes:
      - ./tmp/db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend

  mpath:
    build: .
    depends_on:
      - mysqldb
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    networks:
      - backend

networks:
  backend:
    driver: bridge

