version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: app
    restart: always
    ports:
      - "8443:8443"
    env_file:
      - .env
    environment:
      RAILS_ENV: production
      WEB_CONCURRENCY: 2
      PUMA_PIDFILE: /var/www/mPATH/tmp/pids/server.pid
    volumes:
      - .:/var/www/mPATH
    entrypoint: ["/bin/bash", "/var/www/mPATH/docker/app/entrypoint.sh"]
