version: '3.8'

networks:
  app_network:

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: app
    restart: always
    ports:
      - "8443:8443"
    env_file:
      - .env
    environment:
      RAILS_ENV: production
      DATABASE_HOST: mysql
      PUMA_PORT: 8443
      RAILS_MAX_THREADS: 5
      RAILS_MIN_THREADS: 5
      WEB_CONCURRENCY: 2
      PUMA_PIDFILE: /var/www/mPATH/tmp/pids/server.pid
    networks:
      - app_network
    volumes:
      - .:/var/www/mPATH
    entrypoint: ["/bin/bash", "/var/www/mPATH/docker/app/entrypoint.sh"]

  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app_network

