version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/var/www/mPATH
    depends_on:
      - db
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mpathdb
      MYSQL_USER: mpathuser
      MYSQL_PASSWORD: password
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: