version: '3.8'

networks:
  mpath:

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - mpath
    environment:
      DB_HOST: mysql
      DB_USER: mpath_user
      DB_PASSWORD: mpath_pass
      DB_NAME: mpath
    ports:
      - "3000:3000"

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: mpath
      MYSQL_USER: mpath_user
      MYSQL_PASSWORD: mpath_pass
      MYSQL_ROOT_PASSWORD: root_pass
    networks:
      - mpath
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - app
    networks:
      - mpath
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
