describe('Admin Panel Project', function() {
  before(() => {
    cy.app('clean')
    cy.appScenario('basic')
    cy.login('admin@test.com', 'T3$tAdmin')
    cy.openProjectAP()
  })
  beforeEach(() => {
    cy.get('#tabs').within(() => {
      cy.get('#facilities').contains('Projects').click()
    })
    cy.preserveAllCookiesOnce()
  })
  it('Click on Projects on tabs open Project information page', function() {
    cy.get('#page_title').contains('Project').should('be.visible')
    cy.get('#index_table_facilities').should('be.visible')
    cy.get('#index_table_facilities > tbody > tr').its('length').should('be.eq', 4)
    // cy.get('#logout').click()
  })

  it('Open and close new Project form', function() {
    cy.get('.action_item > a').contains('New Project').click()
    cy.get('#page_title').contains('New Project').should('be.visible')
    cy.get('.cancel > a').contains('Cancel').click()
    // cy.get('#logout').click()
  })

  it('Could not create new Project if name is blank', function() {
    cy.get('.action_item > a').contains('New Project').click()
    cy.get('#page_title').contains('New Project').should('be.visible')
    cy.get('#facility_address_input_gmap > input').type('2-20 Western Rd, Park Royal, London NW10 7LW, UK')
    cy.wait(1000)
    cy.get('#facility_address_input_gmap > input').type('{downarrow} {enter}', {force: true})
    cy.get('#facility_point_of_contact').type('Point of contact').should('have.value', 'Point of contact')
    cy.get('#phone-number__input_phone_number').type('07400 123456')
    cy.get('#facility_email').type('testfacility@mail.com').should('have.value', 'testfacility@mail.com')
    cy.get('#facility_submit_action').contains('Create Project').click()
    cy.get('.errors').contains("Project Name can't be blank")
    cy.get('.inline-errors').contains("can't be blank")
    cy.get('#page_title').contains('New Project').should('be.visible')
    // cy.get('#logout').click()
  })

  it('Could not create new Project if address is blank', function() {
    cy.get('.action_item > a').contains('New Project').click()
    cy.get('#page_title').contains('New Project').should('be.visible')
    cy.get('#facility_facility_name').type('New Test Facility').should('have.value', 'New Test Facility')
    cy.get('#facility_point_of_contact').type('Point of contact').should('have.value', 'Point of contact')
    cy.get('#phone-number__input_phone_number').type('07400 123456')
    cy.get('#facility_email').type('testfacility@mail.com').should('have.value', 'testfacility@mail.com')
    cy.get('#facility_submit_action').contains('Create Project').click()
    cy.get('.errors').contains("Address can't be blank")
    cy.get('#page_title').contains('New Project').should('be.visible')
    // cy.get('#logout').click()
  })

  it('Could not create new Project if Point of contact is blank', function() {
    cy.get('.action_item > a').contains('New Project').click()
    cy.get('#page_title').contains('New Project').should('be.visible')
    cy.get('#facility_facility_name').type('New Test Facility').should('have.value', 'New Test Facility')
    cy.get('#facility_address_input_gmap > input').type('2-20 Western Rd, Park Royal, London NW10 7LW, UK')
    cy.wait(1000)
    cy.get('#facility_address_input_gmap > input').type('{downarrow} {enter}', {force: true})
    cy.get('#phone-number__input_phone_number').type('07400 123456')
    cy.get('#facility_email').type('testfacility@mail.com').should('have.value', 'testfacility@mail.com')
    cy.get('#facility_submit_action').contains('Create Project').click()
    cy.get('.errors').contains("Point of contact can't be blank")
    cy.get('.inline-errors').contains("can't be blank")
    cy.get('#page_title').contains('New Project').should('be.visible')
    // cy.get('#logout').click()
  })

  it('Could not create new Project if Phone number is blank', function() {
    cy.get('.action_item > a').contains('New Project').click()
    cy.get('#page_title').contains('New Project').should('be.visible')
    cy.get('#facility_facility_name').type('New Test Facility').should('have.value', 'New Test Facility')
    cy.get('#facility_address_input_gmap > input').type('2-20 Western Rd, Park Royal, London NW10 7LW, UK')
    cy.wait(1000)
    cy.get('#facility_address_input_gmap > input').type('{downarrow} {enter}', {force: true})
    cy.get('#facility_point_of_contact').type('Point of contact').should('have.value', 'Point of contact')
    cy.get('#facility_email').type('testfacility@mail.com').should('have.value', 'testfacility@mail.com')
    cy.get('#facility_submit_action').contains('Create Project').click()
    cy.get('.errors').contains("Phone number can't be blank")
    cy.get('#page_title').contains('New Project').should('be.visible')
  })

  it('Could not create new Project if email is blank', function() {
    cy.get('.action_item > a').contains('New Project').click()
    cy.get('#page_title').contains('New Project').should('be.visible')
    cy.get('#facility_facility_name').type('New Test Facility').should('have.value', 'New Test Facility')
    cy.get('#facility_address_input_gmap > input').type('2-20 Western Rd, Park Royal, London NW10 7LW, UK')
    cy.wait(1000)
    cy.get('#facility_address_input_gmap > input').type('{downarrow} {enter}', {force: true})
    cy.get('#facility_point_of_contact').type('Point of contact').should('have.value', 'Point of contact')
    cy.get('#phone-number__input_phone_number').type('07400 123456')
    cy.get('#facility_submit_action').contains('Create Project').click()
    cy.get('.errors').contains("Email can't be blank")
    cy.get('#page_title').contains('New Project').should('be.visible')
  })

  it('Sort Project according to Project Name', function() {
    cy.get('.sortable').contains('Project Name').click()
    cy.get('#index_table_facilities > tbody > tr').first().contains('Test Facility 4').should('be.visible')
    cy.get('.sortable').contains('Project Name').click()
    cy.get('#index_table_facilities > tbody > tr').first().contains('Test Facility 1').should('be.visible')
    cy.get('.sortable').contains('Project Name').click()
    cy.get('#index_table_facilities > tbody > tr').first().contains('Test Facility 4').should('be.visible')
  })

  it('Sort Project according to Address', function() {
    cy.get('.sortable').contains('Address').click()
    cy.get('#index_table_facilities > tbody > tr').first().contains('Axford, Marlborough SN8, UK').should('be.visible')
    cy.get('.sortable').contains('Address').click()
    cy.get('#index_table_facilities > tbody > tr').first().contains('2-20 Western Rd, Park Royal, London NW10 7LW, UK').should('be.visible')
    cy.get('.sortable').contains('Address').click()
    cy.get('#index_table_facilities > tbody > tr').first().contains('Axford, Marlborough SN8, UK').should('be.visible')
  })

  it('Sort Project according to Point Of Contact', function() {
    cy.get('.sortable').contains('Point Of Contact').click()
    cy.get('#index_table_facilities > tbody > tr').first().contains('Test points').should('be.visible')
  })

  it('Sort Project according to Email', function() {
    cy.get('.sortable').contains('Email').click()
    cy.get('#index_table_facilities > tbody > tr').first().contains('facility4@test.com').should('be.visible')
    cy.get('.sortable').contains('Email').click()
    cy.get('#index_table_facilities > tbody > tr').first().contains('facility1@test.com').should('be.visible')
    cy.get('.sortable').contains('Email').click()
    cy.get('#index_table_facilities > tbody > tr').first().contains('facility4@test.com').should('be.visible')
  })

  it('Sort Project according to Phone Number', function() {
    cy.get('.sortable').contains('Phone Number').click()
    cy.get('#index_table_facilities > tbody > tr').first().contains('+447400123454').should('be.visible')
    cy.get('.sortable').contains('Phone Number').click()
    cy.get('#index_table_facilities > tbody > tr').first().contains('+447400123451').should('be.visible')
    cy.get('.sortable').contains('Phone Number').click()
    cy.get('#index_table_facilities > tbody > tr').first().contains('+447400123454').should('be.visible')
  })

  it('Search Project by creator', function() {
    cy.get('#index_table_facilities').should('be.visible')
    cy.get('#q_creator_id').select('Test1 Admin')
    cy.get('[type=submit]').first().contains('Filter').click()
    cy.get('#index_table_facilities > tbody > tr').its('length').should('be.eq', 3)
    cy.get('#q_creator_id').select('Test2 Client')
    cy.get('[type=submit]').first().contains('Filter').click()
    cy.get('#index_table_facilities > tbody > tr').its('length').should('be.eq', 1)
    cy.get('#q_creator_id').select('Any')
    cy.get('[type=submit]').first().contains('Filter').click()
    cy.get('#index_table_facilities > tbody > tr').its('length').should('be.eq', 4)
  })

  it('Search Project by facility group', function() {
    cy.get('#index_table_facilities').should('be.visible')
    cy.get('#q_facility_group_id').select('Test Facility Group 1')
    cy.get('[type=submit]').first().contains('Filter').click()
    cy.get('#index_table_facilities > tbody > tr').its('length').should('be.eq', 2)
    cy.get('#q_facility_group_id').select('Test Facility Group 2')
    cy.get('[type=submit]').first().contains('Filter').click()
    cy.get('#index_table_facilities > tbody > tr').its('length').should('be.eq', 2)
    cy.get('#q_facility_group_id').select('Any')
    cy.get('[type=submit]').first().contains('Filter').click()
    cy.get('#index_table_facilities > tbody > tr').its('length').should('be.eq', 4)
  })

  it('Search Project contains name', function() {
    cy.get('#index_table_facilities').should('be.visible')
    cy.get('#q_facility_name').type('Test Facility 1').should('have.value', 'Test Facility 1')
    cy.get('[type=submit]').first().contains('Filter').click()
    cy.get('#search_status_sidebar_section').scrollIntoView()
    cy.get('#search_status_sidebar_section').should('be.visible')
    cy.get('#search_status_sidebar_section > h3').contains('Search status:').should('be.visible')
    cy.get('h4').contains('Current filters:').should('be.visible')
    cy.get('.current_filter').contains('Project Name contains Test Facility 1').should('be.visible')
    cy.get('#index_table_facilities > tbody > tr').its('length').should('be.eq', 1)
    cy.get('.clear_filters_btn').last().contains('Clear Filters').click()
  })

  it('Search Project contains address', function() {
    cy.get('#index_table_facilities').should('be.visible')
    cy.get('#q_address').type('Axford, Marlborough SN8, UK').should('have.value', 'Axford, Marlborough SN8, UK')
    cy.get('[type=submit]').first().contains('Filter').click()
    cy.get('#search_status_sidebar_section').scrollIntoView()
    cy.get('#search_status_sidebar_section').should('be.visible')
    cy.get('#search_status_sidebar_section > h3').contains('Search status:').should('be.visible')
    cy.get('h4').contains('Current filters:').should('be.visible')
    cy.get('.current_filter').contains('Address contains Axford, Marlborough SN8, UK').should('be.visible')
    cy.get('#index_table_facilities > tbody > tr').its('length').should('be.eq', 1)
    cy.get('.clear_filters_btn').last().contains('Clear Filters').click()
  })

  it('Search Project contains point of contact', function() {
    cy.get('#index_table_facilities').should('be.visible')
    cy.get('#q_point_of_contact').type('Test points').should('have.value', 'Test points')
    cy.get('[type=submit]').first().contains('Filter').click()
    cy.get('#search_status_sidebar_section').scrollIntoView()
    cy.get('#search_status_sidebar_section').should('be.visible')
    cy.get('#search_status_sidebar_section > h3').contains('Search status:').should('be.visible')
    cy.get('h4').contains('Current filters:').should('be.visible')
    cy.get('.current_filter').contains('Point of contact contains Test points').should('be.visible')
    cy.get('#index_table_facilities > tbody > tr').its('length').should('be.eq', 4)
    cy.get('.clear_filters_btn').last().contains('Clear Filters').click()
  })

  it('Search Project contains Email', function() {
    cy.get('#index_table_facilities').should('be.visible')
    cy.get('#q_email').type('facility1@test.com').should('have.value', 'facility1@test.com')
    cy.get('[type=submit]').first().contains('Filter').click()
    cy.get('#search_status_sidebar_section').scrollIntoView()
    cy.get('#search_status_sidebar_section').should('be.visible')
    cy.get('#search_status_sidebar_section > h3').contains('Search status:').should('be.visible')
    cy.get('h4').contains('Current filters:').should('be.visible')
    cy.get('.current_filter').contains('Email contains facility1@test.com').should('be.visible')
    cy.get('#index_table_facilities > tbody > tr').its('length').should('be.eq', 1)
    cy.get('.clear_filters_btn').last().contains('Clear Filters').click()
  })

  it('Search Project contains Phone number', function() {
    cy.get('#index_table_facilities').should('be.visible')
    cy.get('#q_phone_number').type('+447400123451').should('have.value', '+447400123451')
    cy.get('[type=submit]').first().contains('Filter').click()
    cy.get('#search_status_sidebar_section').scrollIntoView()
    cy.get('#search_status_sidebar_section').should('be.visible')
    cy.get('#search_status_sidebar_section > h3').contains('Search status:').should('be.visible')
    cy.get('h4').contains('Current filters:').should('be.visible')
    cy.get('.current_filter').contains('Phone number contains +447400123451').should('be.visible')
    cy.get('#index_table_facilities > tbody > tr').its('length').should('be.eq', 1)
    cy.get('.clear_filters_btn').last().contains('Clear Filters').click()
  })

  it('Search Project by state', function() {
    cy.get('#index_table_facilities').should('be.visible')
    cy.get('#q_status').select('inactive')
    cy.get('[type=submit]').first().contains('Filter').click()
    cy.get('.blank_slate').contains('No Projects found').should('be.visible')
    cy.get('#q_status').select('active')
    cy.get('[type=submit]').first().contains('Filter').click()
    cy.get('#index_table_facilities > tbody > tr').its('length').should('be.eq', 4)
    cy.get('#q_status').select('Any')
    cy.get('[type=submit]').first().contains('Filter').click()
    cy.get('#index_table_facilities > tbody > tr').its('length').should('be.eq', 4)
  })

  it('Delete Project', function() {
    cy.get('#index_table_facilities').should('be.visible')
    cy.get('#index_table_facilities > tbody > tr').first().within(() => {
      cy.get('.col-actions').contains('Delete').click()
    })
    cy.get('.flashes').contains('Project was successfully destroyed.').should('be.visible')
    cy.get('#index_table_facilities > tbody > tr').its('length').should('be.eq', 3)
  })

  // TODO: Fix this test case
  // it('Create new Project', function() {
  //   cy.get('.action_item > a').contains('New Project').click()
  //   cy.get('#page_title').contains('New Project').should('be.visible')
  //   cy.get('#facility_facility_name').type('New Test Facility').should('have.value', 'New Test Facility')
  //   cy.get('#facility_point_of_contact').type('Point of contact').should('have.value', 'Point of contact')
  //   cy.get('#phone-number__input_phone_number').type('07400 123456')
  //   cy.get('#facility_email').type('testfacility@mail.com').should('have.value', 'testfacility@mail.com')

  //   cy.get('#facility_address_input_gmap > input').type('2-20 Western Rd, Park Royal, London NW10 7LW, UK')
  //   cy.wait(1000)
  //   cy.get('#facility_address_input_gmap > input').type('{downarrow} {enter}', {force: false})
  //   cy.wait(2000)
  //   cy.get('#facility_submit_action').contains('Create Project').click()
  //   cy.get('.flashes').contains('Project was successfully created.')
  //   cy.get('#index_table_facilities > tbody > tr').its('length').should('be.eq', 5)
  //   // cy.get('#logout').click()
  // })

})
